#!/bin/sh
################################################################
# file: emcgrep.sh
# author: Richard Luo
# date: 2011/08/27 08:16:28
################################################################

source /home/richard/bin/common/my_cscope_common.sh

emcgrep_config=.emcgrep
source ${HOME}/bin/common/$emcgrep_config
if [ -f $emcgrep_config ];then
    source $PWD/$emcgrep_config
fi

# uniq the suffixs
SUFFIXS=`echo $SUFFIXS | tr " " "\n" | sort | uniq |tr "\n" " "`

cmd_name=`basename $0`
if [ $cmd_name = "emcgrep" ]; then
    find_cmd=$(gen_find_cmd)
    # while getopts ":af" opt; do
    #     case $opt in
    #         a)
    #             echo "-a was triggered!" >&2
    #             find_cmd=$(gen_find_cmd)
    #             break
    #             ;;
    #         f)
    #             find_cmd="find . -type f "
    #             ;;
    #         *)
    #             echo "Invalid option: -$OPTARG" >&2
    #             exit 1
    #             ;;
    #     esac
    # done
else
    find_cmd="find . -type f "
fi


# echo $find_cmd " -o \( -print0 \) " > /tmp/emcgrep.cmd
echo $find_cmd " -print0 " > /tmp/emcgrep.cmd

# cat /tmp/emcgrep.cmd
# echo ""
# echo ""
# echo ""
# echo ""
# echo ""

cat /tmp/emcgrep.cmd >&2
echo "================================================================" >&2
sh /tmp/emcgrep.cmd

# echo "\$@:$@"
# echo "\$1:$1"
#  echo "\$2:$2"
# # echo "\$3:$3"
# # echo "\$#:$#"
# # echo "EXCLUDE_DIRS:[$EXCLUDE_DIRS]"

exit 0
