#!/bin/sh
################################################################
# file: emcgrep.sh
# author: Richard Luo
# date: 2011/08/27 08:16:28
################################################################


# find -iregex '.*\.[techsxj]\(ava\|ex\|ty\|ml\|h\|l\|map\|lds\|p\|c\|x\|inl\)*$' -print0 | xargs -0e grep -nHE 
# emcgrep -iregex '.*\.[techsxj]\(ava\|ex\|ty\|ml\|h\|l\|map\|lds\|p\|c\|x\|inl\)*$' -print0 | xargs -0e grep -nHE 

exclude_file=.emcgrep

if [ -f $exclude_file ];then
    source $PWD/$exclude_file
fi

function gen_exclude_dirs()
{
    if [ "X$EXCLUDE_DIRS" = "X" ]; then
        return 0
    fi

    local cmd=""
    for d in $EXCLUDE_DIRS; do
        d=`basename $d`
        if [ "X$cmd" != "X" ]; then
            cmd="$cmd -o -path './$d'"
        else
            cmd="-path './$d'"
        fi
    done
    echo "$cmd"
}

function gen_find_cmd()
{
    local result=""
    local exclude_dirs=$(gen_exclude_dirs)

    if [ "X$exclude_dirs" != "X" ]; then
        cmd_part_exclude="\\( \\( $exclude_dirs \\) -prune -type f \\)"
        result="find . $cmd_part_exclude"
    else
        result="find . "
    fi

    local suffixs_cmds=""
    if [ "X$suffixs_cmds" != "X" ]; then
        cmd_part_suffix="\\( -type f \\( $suffixs_cmds \\) \\) "
        if [ "X$result" != "X" ]; then
            result="$result -o $cmd_part_suffix"
        else
            result="find . $cmd_part_suffix"
        fi
    fi

    local filenames_cmds=""
    if [ "X$filenames_cmds" != "X" ]; then
        cmd_part_names="\\( -type f \\( $filenames_cmds \\) \\) "
        if [ "X$result" != "X" ]; then
            result="$result -o $cmd_part_names"
        else
            result="find . $cmd_part_names"
        fi
    fi

    # echo "res: $result"
    # exit 100

    if [ "X$result" != "X" ]; then
        echo $result
    else
        echo "can not generate the find command"
        exit 100
    fi
}

# gen_exclude_dirs
# echo "HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH"

find_cmd=$(gen_find_cmd)

echo $find_cmd " -o \( $1 '$2' $3 \) " > /tmp/emcgrep.cmd

# cat /tmp/emcgrep.cmd
# echo ""
# echo ""
# echo ""
# echo ""
# echo ""

sh /tmp/emcgrep.cmd

# echo "\$@:$@"
# echo "\$1:$1"
#  echo "\$2:$2"
# # echo "\$3:$3"
# # echo "\$#:$#"
# # echo "EXCLUDE_DIRS:[$EXCLUDE_DIRS]"

exit 0
