#!/bin/bash
################################################################
# file:   ZShell.sh
# author: Richard Luo
# date:   2012-08-11 21:10:41
################################################################

# set -ix

export ANDROID_PRINTF_LOG="time"
# export ANDROID_PRINTF_LOG="thread"

if [ "$1X" = "X" ]; then
    VDS=0
else
    VDS=1
fi

logfile=zbshell$(date +%Y%m%d-%H%S).log
linkfile=zbshell.log
rm -f /home/richard/ddbs/frameworks/logs/$logfile 
touch /home/richard/ddbs/frameworks/logs/$logfile 
ln -fs /home/richard/ddbs/frameworks/logs/$logfile /home/richard/ddbs/frameworks/$linkfile
# valgrind --log-file=$logfile.valgrind --tool=memcheck --leak-check=full

~/ddbs/out/host/linux-x86/pr/sim/system/bin/Zbshell --vds $VDS 2>&1 | tee /home/richard/ddbs/frameworks/logs/$logfile
# ~/ddbs/out/host/linux-x86/pr/sim/system/bin/Zbshell --vds $VDS 2>&1 | tee /home/richard/ddbs/frameworks/logs/$logfile
